apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fiuh677b5-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fiuh677b5-dotnet-basic-gitops